### ISSUE TITLE
environment.yml is missing

### ISSUE THREAD

**Issue by marksantcroos** [biowdl/bam-to-gvcf#15]
The documentation mentions an `environment.yml`, but that seems to be missing.

**Comment by DavyCats** [comment]
The latest version of the develop branch will use Docker images to run the workflow, therefore, the `environment.yml` is obsolete and was removed. The docs for the develop branch are outdated in this regard.

**Comment by marksantcroos** [comment]
ACK, I was informed by Ruben indeed.
